### ISSUE TITLE
Memory leak when generating thumbnail

### ISSUE THREAD

**Issue by SystemZ** [SystemZ/gotag#1]
For .jpg files it starts with this, then memory seems not to be released
https://github.com/SystemZ/gotag/blob/4a2aaed668ff8a5ca9049515fde35b2253caf2dd/server.go#L214

**Comment by SystemZ** [comment]
Maybe just redirect this task to other app or see how it's made by other devs?
https://github.com/Imgur/mandible

**Comment by kacpersaw** [comment]
Try to use library powered by C library. Maybe this will help.
https://github.com/h2non/bimg

**Comment by SystemZ** [comment]
Fixed in https://github.com/SystemZ/gotag/commit/e472781216da4b5ebdf8e792e90c7d4dc9647839
It was https://github.com/Soreil/video/ package so I removed it for now.
