### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by kacperduras** [SystemZ/gotag#14]
Maybe integration with AppVeyor (CI on Windows)?

**Comment by SystemZ** [comment]
Hi, thanks for the tip but what problems would it solve right now?
Currently there is a windows-free CI pipeline with cross-compile using Travis CI and I think it's better that way.

**Comment by kacperduras** [comment]
```
Currently there is a windows-free CI pipeline with cross-compile using Travis CI and I think it's better that way.
```

Ah, ok. I'm blind D:
